#spring.application.name=fileStorageService
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/e_commerce_db
#spring.datasource.url=jdbc:mysql://eCommerce-db:3307/e_commerce_db
#spring.datasource.username=root
#spring.datasource.password=password
#logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
spring.jackson.serialization.fail-on-empty-beans=false
#spring.jpa.show-sql=true
spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb
